### PR TITLE
Remove singleton stubs

### PR DESCRIPTION
**Pull request by geramirez**
- attempted to reverse the mocks at the end of the tests, but that didn't work
- it looks like we won't be able to stub out models

### CODE REVIEW

**Comment by cailyncodes** [comment]
See my comments in #15

**Comment by cailyncodes** [comment]
Also take a look at https://github.com/ctoec/care-4-kids-auto-notifier/pull/12/commits/2e3d58ea91ab857869ecc332926e4d318dc5277a#diff-9a8a14ebf4f8592f3d9c139c5881edf6R9-R37

**Comment by cailyncodes** [comment]
Do you mind if I close this PR? We have that thread in #12 discussing this - trying to clean up Github

**Comment by geramirez** [comment]
yes let's close this

**Pull request closed without merging**
